### ISSUE TITLE
Escaped . character is generated as any character

### ISSUE THREAD

**Issue by zachwildd** [fent/randexp.js#110]
Hello, the following isn't escaping the . character and generates any character in between the digits instead. 

```typescript
const regExGenerator = new RandExp("[0-9]{3}\.[0-9]{3}");
const myStr = regExGenerator.gen();
```

Some outputs I got from gen:
```
734m669
437x560
722g339
```
 
If you can give some pointers (which files to check) I can try and submit a PR.

Also, it doesn't seem to be working in the float example on the pages site, but it is in the email and lorem ipsum examples.

**Comment by fent** [comment]
hi, this is because in a string, when using the backslash, it escapes the character after it. the above string would evaluate to "[0-9]{3}.[0-9]{3}". you can add an additional backslash to escape the backslash "[0-9]{3}\\.[0-9]{3}".  you can also use a regex `/[0-9]{3}\.[0-9]{3}/`



> Also, it doesn't seem to be working in the float example on the pages site

the fractional side is optional, so it only shows up half the time

**Comment by zachwildd** [comment]
Thanks so much.
