### ISSUE TITLE
Negate RegExp

### ISSUE THREAD

**Issue by sunupf** [fent/randexp.js#15]
Hi, 

I trying to generate based on /^((?![0-9]).)*$/ , it shoud be valid if there is no number on the string, and I try this expression on randexp

$ node -i
> var randexp = require('randexp')
> new randexp(/^((?![0-9]).)*$/).gen()
';vpqBpM+e~BJS2H#.W#G:q3tMdw~MaU\\uTJ,bhG'

but when I test the result it's return false.
> /^((?![0-9]).)*$/.test(';vpqBpM+e~BJS2H#.W#G:q3tMdw~MaU\\uTJ,bhG')
false

Thanks,

**Comment by fent** [comment]
I am not sure if this is an error with randexp, but I'm confused with the use of `?!` with nothing preceding it, and why it would compile.

Why not use `/^[^0-9]*$/`?

**Comment by sunupf** [comment]
actually 0-9 is just for test, i want replace it using another pattern which can be complex. 

I just try too negate regexp that user inputed. that's why I use ?!

**Comment by fent** [comment]
Right now, randexp ignores groups that use the `x(?!y)` syntax. it prints a blank string for them. should it be printing something that does NOT match whatever is inside?

It's a confusing rule, `/x(?!y)/.test('x')` is `true`, as well as `/x(?!y)/.test('xz')`. It looks like `x` would be fine by itself if there is nothing after the group, otherwise it has to make sure whatever is after it also does not match the group.
